### ISSUE TITLE
Work with native app?

### ISSUE THREAD

**Issue by martingg88** [malikov/Authenticate.me-client-cordova-ionic#1]
does it work with native social app (etc: facebook) instead of inappbrowser?

**Comment by malikov** [comment]
not yet. To make it work with native social sdk you'll have to login using the social sdk then send the access token to the server to save it etc... I'll try something out for facebook in the weeks to come. But I kind of dislike this way of login in which is client side oriented rather than server side oriented.

**Comment by martingg88** [comment]
great work....thanks.

**Comment by malikov** [comment]
Hey @martingg88 have you tested it on a iOS device or android ? Just upgraded to the new iOS 8.0 on my iphone 4s it seems a few things are broken. Can you let me know ? Android should work fine.

**Comment by martingg88** [comment]
not yet... I tot wana integrate this to my project once the native login is ready...

**Comment by malikov** [comment]
@martingg88 never mind it had something to do with cordova 3.5.0 inAppbrowser was broken, you'll need to update to 3.6.0 for the whole thing to work. Hmmm for the native login this is not high priority for me right now so you might wait a while :) However if you're able to get it done before I do let me know I'll merge your code in

**Comment by martingg88** [comment]
sure..thanks

**Comment by chegoon** [comment]
It looks great. Can you test this in laptop? I just opened index.html in browser. It always show the message, 'Loading...' with those messages in console. XMLHttpRequest can not load.... I am newbie in scripts... sorry

**Comment by malikov** [comment]
Hey @chegoon ,

can you describe the error you're seing ? It should work just fine on your localhost. I'm assuming here you've used something like nginx or xampp to run a local server and have opened index.html on this server, did you ? Or did you just clone the repo and opened the index.html file in which case it won't work

**Comment by malikov** [comment]
@martingg88 any progress with native ?

**Comment by martingg88** [comment]
no..i'm give up the Hybrid app development due to the performance issue. I'm doing native app development for android now..

**Comment by chegoon** [comment]
@malikov thanks for notify and sorry for late response. As you told me in the reply, I didn't code 'ionic serve' and just clicked index.html. It worked in the mobile. Thanks

**Comment by malikov** [comment]
@martingg88 :) mind sharing your native solution for native android in a repo...

**Comment by martingg88** [comment]
@malikov... i haven't reach the phase. let you know once I have finished it. do you have skype..maybe we can keep a contact there.
