### ISSUE TITLE
Haven't the last version of Ionic

### ISSUE THREAD

**Issue by sinner** [malikov/Authenticate.me-client-cordova-ionic#3]
The last version of ionic give us with the ngResource tool by default, Do you plan to upgrade the version of Ionic?

**Comment by malikov** [comment]
hmm I'm thinking you can easily upgrade the version of ionic from beta 11 (that I'm using) to beta 13 by changing the bower.json file to

```
{
  "name": "Authenticate.me",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.0.0-beta.13"
  }
}
```

and call bower update (or install, I'm not sure) this will update ionic to the latest version. However before doing so I'd suggest you look at the release to see if there's any breaking changes (https://github.com/driftyco/ionic/releases). I didn't use ngResource but favored $http instead.
