### ISSUE TITLE
have you tested with ionic beta 14?

### ISSUE THREAD

**Issue by BANG88** [malikov/Authenticate.me-client-cordova-ionic#6]
I got  some issues on `app.start` state and I can not figure out the issue,need your help :sos:  

```
 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.6/$rootScope/infdig?p0=10&p1=%5B%5D
```

**Comment by BANG88** [comment]
@malikov  I have found a solution here https://github.com/angular-ui/ui-router/issues/600#issuecomment-47228922

**Comment by malikov** [comment]
thanks for sharing @littlebang I haven't tested this with beta-14 this solution will be helpful for other projects
